[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "out"

[build.environment]
  STATIC_EXPORT = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

